# -*- coding: utf-8 -*-
"""Green_Index.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LN98uJIaGFaZX7YAmHUpITdybH0tJvdG
"""

import pandas as pd
from datetime import datetime as dt
import urllib.request
import json
dataframes = []
def green_g(assets):
    def esg_data(symbol):
        dataframes = []
        url = f"https://query2.finance.yahoo.com/v1/finance/esgChart?symbol={symbol}"

        connection = urllib.request.urlopen(url)

        data = connection.read()
        data_2 = json.loads(data)
        Formatdata = data_2["esgChart"]["result"][0]["symbolSeries"]
        Formatdata_2 = pd.DataFrame(Formatdata)
        Formatdata_2["timestamp"] = pd.to_datetime(Formatdata_2["timestamp"], unit="s")
        print("Comapany: ", symbol)
        print(Formatdata_2.head())
        return Formatdata_2

    assets = assets
    above_g = []
    for i in range(len(assets)):
        df = esg_data(assets[i])
        above_g.append(round(df["esgScore"][:60].mean()/100,2))
    return above_g

